{% set name = "vgorient" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/whelixw/vgOrient.git"
  git_rev: "develop"

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - cp cut_and_rot.py $PREFIX/bin/
    - cp VG_diterative.py $PREFIX/bin/
    - cp kmer_jaccard.py $PREFIX/bin/
    - cp jaccard_dit_wrapper.py $PREFIX/bin/
    - chmod +x $PREFIX/bin/cut_and_rot.py
    - chmod +x $PREFIX/bin/VG_diterative.py
    - chmod +x $PREFIX/bin/kmer_jaccard.py
    - chmod +x $PREFIX/bin/jaccard_dit_wrapper.py

requirements:
  host:
    - python >=3.8,<3.12
  run:
    - python >=3.8,<3.12
    - vg
    - biopython >=1.83
    - networkx >=3.3
    - numpy >=1.26.4
    # Include any other dependencies if required

test:
  commands:
    #- cut_and_rot.py --help
    #- VG_diterative.py --help
    #- kmer_jaccard.py --help
    - jaccard_dit_wrapper.py --help

about:
  home: "https://github.com/whelixw/vgOrient"
  license: "MIT"
  summary: "Scripts for processing mitochondrial graphs."

extra:
  recipe-maintainers:
    - whelixw  # Replace with your GitHub username if different
